---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: path={{ item.certificate_file }}
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Include local tasks for ssl template and certbot
  include_tasks: "certbot_ssl.yml"
  
- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ item.servername}}.conf"
    owner: root
    group: root
    mode: 0644
    validate: "httpd -t -f %s"
  notify: restart apache
  when: apache_create_vhosts
  vars:
    current_vhost: "{{ item.servername }}"
  with_items: " {{ apache_vhosts }}"

